global:
  resolve_timeout: 5m
  smtp_hello: "localhost"
  smtp_require_tls: true

route:
  receiver: email

receivers:
  - name: email
    email_configs:
      - send_resolved: false
        to: kingsamuel412@gmail.com
        from: melvinsamuel070@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: melvinsamuel070@gmail.com
        auth_password: "zihv khej dtsh ostz"  # Reference an environment variable
        require_tls: true
