# route:
#   group_by: ['alertname']
#   receiver: email
#   routes:
#     - match:
#         severity: 'critical'
#       receiver: critical-email
#     - match:
#         severity: 'warning'
#       receiver: warning-email

# receivers:
#   - name: email
#     email_configs:
#       - send_resolved: true
#         to: kingsamuel412@gmail.com
#         from: melvinsamuel070@gmail.com
#         smarthost: smtp.gmail.com:587
#         auth_username: melvinsamuel070
#         auth_password: "dygc wdan sqar siby"
#         require_tls: true
#         tls_config:
#           insecure_skip_verify: false
#   - name: critical-email
#     email_configs:
#       - send_resolved: true
#         to: kingsamuel412@gmail.com
#         from: melvinsamuel070@gmail.com
#         smarthost: smtp.gmail.com:587
#         auth_username: melvinsamuel070
#         auth_password: "dygc wdan sqar siby"
#         require_tls: true
#         tls_config:
#           insecure_skip_verify: false
#   - name: warning-email
#     email_configs:
#       - send_resolved: true
#         to: kingsamuel412@gmail.com
#         from: melvinsamuel070@gmail.com
#         smarthost: smtp.gmail.com:587
#         auth_username: melvinsamuel070
#         auth_password: "dygc wdan sqar siby"
#         require_tls: true
#         tls_config:
#           insecure_skip_verify: false
























# global:
#   resolve_timeout: 1m
#   smtp_require_tls: true  # Ensures TLS encryption for email

# route:
#   receiver: email

# receivers:
#   - name: email
#     email_configs:
#       - send_resolved: true
#         to: kingsamuel412@gmail.com
#         from: melvinsamuel070@gmail.com
#         smarthost: smtp.gmail.com:587  # SMTP server for Gmail (port 587 for TLS)
#         auth_username: melvinsamuel070@gmail.com
#         auth_password: "dygc wdan sqar siby"  # Your Gmail App password
#         require_tls: true  # TLS for encryption
#         tls_config:
#           insecure_skip_verify: false  # Ensure verification unless you have certificate issues

global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'melvinsamuel070@gmail.com'
  smtp_auth_username: 'melvinsamuel070@gmail.com'
  smtp_auth_password: 'dygc wdan sqar siby'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  receiver: 'email-alerts'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'kingsamuel412@gmail.com'
        send_resolved: true
