groups:
  - name: test-alerts
    rules:
      - alert: PrometheusDown
        expr: up == 0
        for: 1m
        annotations:
          summary: "Prometheus instance is down!"

      - alert: FrontendDown
        expr: up == 0
        for: 1m
        annotations:
          summary: "Frontend service is down!"

      - alert: BackendDown
        expr: up == 0
        for: 1m
        annotations:
          summary: "Backend service is down!"    

      
      

      
      
