groups:
  - name: service_health_alerts
    rules:
      - alert: FrontendDown
        expr: up{job="mern_todo-frontend-1"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Frontend service is down"
          description: "The frontend service has been down for more than 5 minutes."

      - alert: BackendDown
        expr: up{job="mern_todo-backend-1"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Backend service is down"
          description: "The backend service has been down for more than 5 minutes."
