name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  AWS_REGION: us-east-1
  BACKEND_IMAGE: melvinsamuel070/backend:latest
  FRONTEND_IMAGE: melvinsamuel070/frontend1:latest
  ALERTMANAGER_URL: http://localhost:9092/api/v2/alerts
  DOMAIN_NAME: melvinsamuel070.xyz  # Add your domain name here
  EMAIL: melvinsamuel070@gmail.com  # Add your email for Certbot registration

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.INSTANCE_IP }} >> ~/.ssh/known_hosts
        env:
            AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        
      # Step 3: Install Docker and Dependencies on EC2 Instance with Debugging
      - name: Install Docker and Dependencies on EC2 Instance with Debugging
        run: |
          
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.INSTANCE_IP }} "echo 'SSH connection successful'"
      
          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
            set -x
            trap 'echo "Error occurred at line $LINENO"' ERR

            # Update DNS settings
            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
            echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf > /dev/null
            sudo sed -i "1s/^/127.0.0.1 $(hostname)\n/" /etc/hosts

            # Install required packages
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

            # Docker installation
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            if sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin; then
              echo "Docker installation succeeded."
            else
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
            fi

            # Enable Docker service
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo apt-get install -y docker-compose-plugin
            sudo usermod -aG docker $USER
            set +x
          EOF

      # Step 4: Install and Configure Nginx on EC2 Instance with SSL (Certbot)
      - name: Install and Configure Nginx with SSL for melvinsamuel070.xyz
        run: |
          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
            set -x
            trap 'echo "Error occurred at line $LINENO"; exit 1' ERR
            
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
          set -x
          trap 'echo "Error occurred at line $LINENO"; exit 1' ERR
 
           # Run dpkg configuration and proceed with other steps
           sudo dpkg --configure -a
           # Additional commands...
          EOF



            # Update package lists and install Nginx
            sudo apt-get update
            sudo apt-get install -y nginx

            # Install Certbot and Nginx plugin
            sudo apt-get install -y certbot python3-certbot-nginx

            # Enable and start Nginx service
            sudo systemctl enable nginx
            sudo systemctl start nginx

            # Obtain SSL certificate with Certbot
            sudo certbot --nginx -d melvinsamuel070.xyz --non-interactive --agree-tos --email melvinsamuel070@gmail.com

            # Test Nginx configuration
            sudo nginx -t

            # Reload Nginx service to apply changes
            sudo systemctl reload nginx
          EOF

      # Step 5: Configure Nginx Reverse Proxy
      - name: Configure Nginx Reverse Proxy for Frontend and Backend
        run: |
          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
            set -x
            trap 'echo "Error occurred at line $LINENO"' ERR

            # Nginx Configuration
            echo 'server {
              listen 80;
              server_name melvinsamuel070.xyz;
              return 301 https://$host$request_uri;
            }

            server {
              listen 443 ssl;
              server_name melvinsamuel070.xyz;

              ssl_certificate /etc/letsencrypt/live/melvinsamuel070.xyz/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/melvinsamuel070.xyz/privkey.pem;

              location / {
                proxy_pass http://localhost:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
              }

              location /api/ {
                proxy_pass http://localhost:3500;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
              }
            }' | sudo tee /etc/nginx/sites-available/default > /dev/null

            # Test Nginx configuration and reload
            sudo nginx -t
            sudo systemctl reload nginx

            set +x
          EOF

      # Step 6: Start Docker Compose on EC2 with Debugging
      - name: Start Docker Compose on EC2 with Debugging
        run: |
          ssh -o StrictHostKeyChecking=no -i "/home/ubuntu/.ssh/id_rsa" ubuntu@${{ secrets.INSTANCE_IP }} <<'EOF'
            set -x
            trap 'echo "Error occurred at line $LINENO"' ERR

            # Resolve any dpkg lock issues before starting Docker installation
            sudo dpkg --configure -a
            sudo apt-get install -f -y  # Attempt to fix broken dependencies

            # Update package lists
            sudo apt-get update

            # Check if Docker and Docker Compose are installed, and install if necessary
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing..."
              sudo apt-get install -y docker.io
            fi

            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing..."
              sudo apt-get install -y docker-compose
            fi

            # Navigate to project directory and start Docker Compose
            cd /home/ubuntu/MERN_Todo_app
            sudo docker-compose up -d

            set +x
          EOF

      # Step 7: Send Email Notification for Deployment Success
      - name: Send Email Notification for Deployment Success
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment Success: CD Pipeline"
          body: "The deployment of your application completed successfully."
          to: kingsamuel412@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
